name: 'Setup Python Project + Run Unit Tests'
description: 'Reusable action to setup python, poetry and project dependencies in a standard way.'
runs:
  using: "composite"
  steps:
    - name: Setup Python Project
      uses: joshorr/workflows/py-setup-project@main

    - name: Run tests
      if: env.PKG_MANAGER == 'uv'
      shell: bash
      run: uv run pytest

    - name: Run tests
      if: env.PKG_MANAGER == 'poetry'
      shell: bash
      run: poetry run pytest
