name: 'Setup Python, Poetry and Project Deps'
description: 'Reusable action to setup python, poetry and project dependencies in a standard way.'
runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #       Check-out repo, set-up python + poetry
    #----------------------------------------------
    - name: Checkout Repo
      uses: actions/checkout@v6

    - name: Detect Package Manager
      shell: bash
      run: |
        if [ -f "uv.lock" ]; then
          echo "Detected package manager: uv"
          echo "PKG_MANAGER=uv" >> "$GITHUB_ENV"
        else
          echo "Detected package manager: poetry"
          echo "PKG_MANAGER=poetry" >> "$GITHUB_ENV"
        fi
    #----------------------------------------------
    #         Poetry Based Project
    #----------------------------------------------
    - name: Install uv
      if: env.PKG_MANAGER == 'uv'
      uses: astral-sh/setup-uv@v8.3.2
    - name: Install UV Dependencies
      if: env.PKG_MANAGER == 'uv'
      shell: bash
      # This will install the correct version of python for us automatically.
      run: uv sync

    #----------------------------------------------
    #         Poetry Based Project
    #----------------------------------------------
    - name: Install poetry
      if: env.PKG_MANAGER == 'poetry'
      shell: bash
      run: pipx install poetry
    - name: Read Needed Python Version
      if: env.PKG_MANAGER == 'poetry'
      shell: bash
      run: |
        PY_VER=$(sed -n 's/^ *python *= *"[~^]*\([0-9\.]*\)"/\1/p' pyproject.toml)
        echo "PY_VERSION=$PY_VER" >> $GITHUB_ENV
    - name: Setup Poetry's Python v${{ env.PY_VERSION }}
      if: env.PKG_MANAGER == 'poetry'
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PY_VERSION }}
        cache: poetry
    - name: Install Dependencies
      if: env.PKG_MANAGER == 'poetry'
      shell: bash
      run: poetry install --no-interaction --no-root
    - name: Install Self
      if: env.PKG_MANAGER == 'poetry'
      shell: bash
      run: poetry install --no-interaction
